#-*-coding:utf-8
ALL_SYNTAX=[
	('ABAP', 'abap', u'ABAP（高级商务应用编程）是一种高级编程语言，由德国软件公司SAP开发。目前，和最近引入的Java一起，ABAP主要用作SAP的编程'),
	('ANTLR', 'antlr', u'Antlr 是一个基于 Java 开发的功能强大的语言识别工具，Antlr 以其简介的语法和高速的运行效率在这类工具中出类拔萃。'),
	('ANTLR With ActionScript Target', 'antlr', u''),
	('ANTLR With C# Target', 'antlr'),
	('ANTLR With CPP Target', 'antlr'),
	('ANTLR With Java Target', 'antlr'),
	('ANTLR With ObjectiveC Target', 'antlr'),
	('ANTLR With Perl Target', 'antlr'),
	('ANTLR With Python Target', 'antlr'),
	('ANTLR With Ruby Target', 'antlr'),
	('ActionScript', 'actionscript', u'Flash用的语言'),
	('ActionScript 3', 'actionscript3', u''),
	('Ada', 'ada'),
	('ApacheConf', 'apacheconf', u'Apache配置文件'),
	('AppleScript', 'applescript', u'苹果的脚本语言'),
	('Asymptote', 'asymptote'),
	('BBCode', 'bbcode'),
	('Bash', 'bash', u'Bash脚本'),
	('Bash Session', 'bash'),
	('Batchfile', 'batchfile'),
	('Befunge', 'befunge'),
	('BlitzMax', 'blitzMax'),
	('Boo', 'boo'),
	('Brainfuck', 'brainfuck'),
	('C', 'c', u'经典的C语言, 没什么好说的'),
	('C#', 'csharp', u'C#, .NET的默认语言'),
	('C++', 'c++'),
	('CMake', 'cmake'),
	('CSS', 'css', u'网页格式化脚本'),
	('CSS+Django/Jinja', 'css'),
	('CSS+Genshi Text', 'css'),
	('CSS+Mako', 'css'),
	('CSS+Myghty', 'css'),
	('CSS+PHP', 'css'),
	('CSS+Ruby', 'css'),
	('CSS+Smarty', 'css'),
	('Cheetah', 'cheetah'),
	('Clojure', 'clojure'),
	('CoffeeScript', 'coffeescript'),
	('Coldfusion HTML', 'coldfusion'),
	('Common Lisp', 'commonlisp', u'Lisp, 一个古老而神奇的语言'),
	('Cython', 'cython'),
	('D', 'd'),
	('Darcs Patch', 'darcs'),
	('Debian Control file', 'debian'),
	('Debian Sourcelist', 'debian'),
	('Delphi', 'delphi'),
	('Diff', 'diff'),
	('Django/Jinja', 'django'),
	('Duel', 'duel'),
	('Dylan', 'dylan'),
	('ERB', 'erb'),
	('Embedded Ragel', 'ragel'),
	('Erlang', 'erlang'),
	('Erlang erl session', 'erlang'),
	('Evoque', 'evoque'),
	('Factor', 'factor'),
	('Felix', 'felix'),
	('Fortran', 'fortran'),
	('GAS', 'gas'),
	('GLSL', 'glsl'),
	('Genshi', 'genshi'),
	('Genshi Text', 'genshi'),
	('Gettext Catalog', 'gettext'),
	('Gherkin', 'gherkin'),
	('Gnuplot', 'gnuplot'),
	('Go', 'go'),
	('GoodData-CL', 'gooddata-cl'),
	('Groff', 'groff'),
	('HTML', 'html', u'超文本标记语言, 做网站必会哦'),
	('HTML+Cheetah', 'html'),
	('HTML+Django/Jinja', 'html'),
	('HTML+Evoque', 'html'),
	('HTML+Genshi', 'html'),
	('HTML+Mako', 'html'),
	('HTML+Myghty', 'html'),
	('HTML+PHP', 'html'),
	('HTML+Smarty', 'html'),
	('HTML+Velocity', 'html'),
	('Haml', 'haml'),
	('Haskell', 'haskell'),
	('Hybris', 'hybris'),
	('INI', 'ini'),
	('IRC logs', 'irc'),
	('Io', 'io'),
	('Ioke', 'ioke'),
	('Jade', 'jade'),
	('Java', 'java', u'Sun公司出品的语言, 工业化标准'),
	('Java Server Page', 'jsp'),
	('JavaScript', 'javascript'),
	('JavaScript+Cheetah', 'javascript'),
	('JavaScript+Django/Jinja', 'javascript'),
	('JavaScript+Genshi Text', 'javascript'),
	('JavaScript+Mako', 'javascript'),
	('JavaScript+Myghty', 'javascript'),
	('JavaScript+PHP', 'javascript'),
	('JavaScript+Ruby', 'javascript'),
	('JavaScript+Smarty', 'javascript'),
	('LLVM', 'llvm'),
	('Lighttpd configuration file', 'lighttpd', u'Lighttpd配置文本'),
	('Literate Haskell', 'haskell'),
	('Logtalk', 'logtalk'),
	('Lua', 'lua'),
	('MAQL', 'maql'),
	('MOOCode', 'moocode'),
	('MXML', 'mxml'),
	('Makefile', 'makefile', u'编译配置脚本'),
	('Mako', 'mako'),
	('Mason', 'mason'),
	('Matlab', 'matlab'),
	('Matlab session', 'matlab'),
	('MiniD', 'minid'),
	('Modelica', 'modelica'),
	('Modula-2', 'modula2'),
	('MoinMoin/Trac Wiki markup', 'trac', u'MoinMoin和Trac的wiki支持的描述语言'),
	('MuPAD', 'mupad'),
	('MySQL', 'mysql'),
	('Myghty', 'myghty'),
	('NASM', 'nasm'),
	('Newspeak', 'newspeak'),
	('Nginx configuration file', 'nginx', u'nginx配置文件'),
	('NumPy', 'numpy'),
	('OCaml', 'ocaml'),
	('Objective-C', 'objective-c'),
	('Objective-J', 'objective-j'),
	('Ooc', 'ooc'),
	('PHP', 'php', u'最流行的web开发语言'),
	('POVRay', 'povray'),
	('Perl', 'perl', u'黑客最爱用的语言'),
	('PostScript', 'postscript'),
	('Prolog', 'prolog'),
	('Properties', 'properties'),
	('Protocol Buffer', 'protocol'),
	('Python', 'python'),
	('Python 3', 'python3'),
	('Python 3.0 Traceback', 'python3'),
	('Python Traceback', 'python'),
	('Python console session', 'python'),
	('RConsole', 'RConsole'),
	('REBOL', 'rebol'),
	('RHTML', 'rhtml'),
	('Ragel', 'ragel'),
	('Ragel in C Host', 'ragel'),
	('Ragel in CPP Host', 'ragel'),
	('Ragel in D Host', 'ragel'),
	('Ragel in Java Host', 'ragel'),
	('Ragel in Objective C Host', 'ragel'),
	('Ragel in Ruby Host', 'ragel'),
	('Raw token data', 'raw'),
	('Redcode', 'redcode'),
	('Ruby', 'ruby', u'Ruby编程语言'),
	('Ruby irb session', 'ruby'),
	('S', 's'),
	('SCSS', 'scss'),
	('SQL', 'sql', u'SQL语言, 数据库查询语言'),
	('Sass', 'sass'),
	('Scala', 'scala'),
	('Scalate Server Page', 'scala'),
	('Scaml', 'scaml'),
	('Scheme', 'scheme'),
	('Smalltalk', 'Smalltalk'),
	('Smarty', 'smarty', u'PHP的一个模版'),
	('SquidConf', 'squidconf'),
	('Tcl', 'tcl'),
	('Tcsh', 'tcsh'),
	('TeX', 'tex'),
	('Text only', 'text', u'普通文本'),
	('VB.net', 'vbnet'),
	('Vala', 'vala'),
	('Velocity', 'Velocity'),
	('VimL', 'viml', u'Vim插件脚本'),
	('XML', 'xml', u'扩展标记语言, 目前最流行的数据格式'),
	('XML+Cheetah', 'xml'),
	('XML+Django/Jinja', 'xml'),
	('XML+Evoque', 'xml'),
	('XML+Mako', 'xml'),
	('XML+Myghty', 'xml'),
	('XML+PHP', 'xml'),
	('XML+Ruby', 'xml'),
	('XML+Smarty', 'xml'),
	('XML+Velocity', 'xml'),
	('XQuery', 'xquery'),
	('XSLT', 'xslt'),
	('YAML', 'yaml', u'目前比较流行的配置文件格式'),
	('aspx-cs', 'aspx-cs'),
	('aspx-vb', 'aspx-vb'),
	('autohotkey', 'autohotkey'),
	('c-objdump', 'c-objdump'),
	('cfstatement', 'cfstatement'),
	('cpp-objdump', 'cpp-objdump'),
	('d-objdump', 'd-objdump'),
	('haXe', 'haxe'),
	('objdump', 'objdump'),
	('reStructuredText', 'reStructuredText'),
	('sqlite3con', 'sqlite3con'),
	('verilog', 'verilog'),
]
